/*
 * This class was generated by the JDS command line tool.
 * 
 * It was created by the user SBSS_19220038074936318185415652640319701600333637668158810727543328814
 * on the HANA system mo-d34b9d109:30015 for CDS entities contained inside the schema
 * 3F15CB45A62849F8834FFBA2B4C866CB.
 * 
 * 
 */
package com.sap.iot.ain.rules.models;

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.sap.iot.ain.reuse.SystemAdministrativeData;
import com.sap.iot.ain.reuse.SystemAdministrativeDataAccess;
import com.sap.iot.ain.reuse.SystemAdministrativeDataEventListener;

@Entity
@Table(name = "\"sap.ain.metaData::Rules.Rule\"")
@XmlRootElement
@EntityListeners({SystemAdministrativeDataEventListener.class})
@IdClass(RulePK.class)
@JsonIgnoreProperties(ignoreUnknown = true)
public class Rule implements Serializable, SystemAdministrativeDataAccess {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "\"Client\"", nullable = true, length = 32)
	private String client;

	@Id
	@Column(name = "\"ID\"", nullable = true, length = 32)
	private String id;

	@Column(name = "\"Name\"", nullable = true, length = 255)
	private String name;

	@Column(name = "\"Description\"", nullable = true, length = 200)
	private String description;

	@Column(name = "\"RuleType\"", nullable = true, length = 10)
	private String ruleType;

	@Column(name = "\"Priority\"", nullable = true, length = 100)
	private String priority;

	@Column(name = "\"IsEnabled\"", nullable = true, length = 10)
	private String isEnabled;

	@Column(name = "\"TenantSubDomain\"", nullable = true, length = 100)
	private String tenantSubDomain;
	
	@Column(name = "\"RuleExpression\"", nullable = true, length = 5000)
	private String ruleExpression;

	@Embedded
	private SystemAdministrativeData systemAdministrativeData = new SystemAdministrativeData();

	public String getClient() {
		return client;
	}

	public void setClient(String client) {
		this.client = client;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getRuleType() {
		return ruleType;
	}

	public void setRuleType(String ruleType) {
		this.ruleType = ruleType;
	}

	public String getPriority() {
		return priority;
	}

	public void setPriority(String priority) {
		this.priority = priority;
	}

	public String getIsEnabled() {
		return isEnabled;
	}

	public void setIsEnabled(String isEnabled) {
		this.isEnabled = isEnabled;
	}

	public SystemAdministrativeData getSystemAdministrativeData() {
		return systemAdministrativeData;
	}

	public void setSystemAdministrativeData(SystemAdministrativeData systemAdministrativeData) {
		this.systemAdministrativeData = systemAdministrativeData;
	}



	public String getTenantSubDomain() {
		return tenantSubDomain;
	}

	public void setTenantSubDomain(String tenantSubDomain) {
		this.tenantSubDomain = tenantSubDomain;
	}
	
	public String getRuleExpression() {
		return ruleExpression;
	}

	public void setRuleExpression(String ruleExpression) {
		this.ruleExpression = ruleExpression;
	}


	@Override
	public int hashCode() {
		int hash = 7;
		hash = 17 * hash + Objects.hashCode(this.client);
		hash = 17 * hash + Objects.hashCode(this.id);
		hash = 17 * hash + Objects.hashCode(this.name);
		hash = 17 * hash + Objects.hashCode(this.description);
		hash = 17 * hash + Objects.hashCode(this.ruleType);
		hash = 17 * hash + Objects.hashCode(this.priority);
		hash = 17 * hash + Objects.hashCode(this.isEnabled);
		hash = 17 * hash + Objects.hashCode(this.systemAdministrativeData);
		hash = 17 * hash + Objects.hashCode(this.ruleExpression);
		return hash;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		final Rule other = (Rule) obj;
		if (!Objects.equals(this.client, other.client)) {
			return false;
		}
		if (!Objects.equals(this.id, other.id)) {
			return false;
		}
		if (!Objects.equals(this.name, other.name)) {
			return false;
		}
		if (!Objects.equals(this.description, other.description)) {
			return false;
		}
		if (!Objects.equals(this.ruleType, other.ruleType)) {
			return false;
		}
		if (!Objects.equals(this.priority, other.priority)) {
			return false;
		}
		if (!Objects.equals(this.isEnabled, other.isEnabled)) {
			return false;
		}
		if (!Objects.equals(this.systemAdministrativeData, other.systemAdministrativeData)) {
			return false;
		}
		if (!Objects.equals(this.ruleExpression, other.ruleExpression)) {
			return false;
		}
		return true;
	}

	@Override
	public String toString() {
		return "Rule{" + "client=" + client + ", id=" + id + ", name=" + name + ", description="
				+ description + ", ruleType=" + ruleType + ", priority=" + priority + ", isEnabled="
				+ isEnabled + ", systemAdministrativeData=" + systemAdministrativeData
				+ ", tenantSubDomain=" + tenantSubDomain 
				+ ", ruleExpression=" +  ruleExpression +'}';
	}

}
