/*
 * This class was generated by the JDS command line tool.
 *
 * It was created by the user SBSS_19220038074936318185415652640319701600333637668158810727543328814
 * on the HANA system mo-d34b9d109:30015
 * for CDS entities contained inside the schema 3F15CB45A62849F8834FFBA2B4C866CB.
 *
 * Time of creation: 2016/10/05 16:01:42
 *
 */
package com.sap.iot.ain.rules.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import java.io.BufferedReader;
import java.io.Serializable;
import java.util.Objects;
import javax.persistence.IdClass;

@Entity
@Table(name = "\"sap.ain.metaData::Rules.RuleAction\"")
@IdClass(RuleActionPK.class)
@JsonIgnoreProperties(ignoreUnknown = true)
public class RuleAction implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @Column(name = "\"Client\"", nullable = true, length = 32)
    private String client;

    @Id
    @Column(name = "\"ID\"", nullable = true, length = 255)
    private String id;

    @Column(name = "\"Type\"", length = 200)
    private String type;

    @Column(name = "\"RuleID\"", length = 200)
    private String ruleID;

    @Column(name = "\"Name\"", length = 200)
    private String name;

    @Column(name = "\"MultipleEmails\"", length = 1)
    private String multipleEmails;

    @Column(name = "\"Description\"", length = 200)
    private String description;

    @Column(name = "\"ActionParams\"", length = 1000)
    private String actionParams;

    @Column(name = "\"ActionID\"", length = 200)
    private String actionId;

    @Column(name = "\"AlertTypeID\"", length = 81)
    private String alertTypeId;
    
    public String getClient() {
        return client;
    }

    public void setClient(String client) {
        this.client = client;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getRuleID() {
        return ruleID;
    }

    public void setRuleID(String ruleID) {
        this.ruleID = ruleID;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getMultipleEmails() {
        return multipleEmails;
    }

    public void setMultipleEmails(String multipleEmails) {
        this.multipleEmails = multipleEmails;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getActionParams() {
        return actionParams;
    }

    public void setActionParams(String actionParams) {
        this.actionParams = actionParams;
    }

    public String getActionId() {
        return actionId;
    }

    public void setActionId(String actionId) {
        this.actionId = actionId;
    }

    public String getAlertTypeId() {
		return alertTypeId;
	}

	public void setAlertTypeId(String alertTypeId) {
		this.alertTypeId = alertTypeId;
	}

	@Override
    public int hashCode() {
        int hash = 5;
        hash = 89 * hash + Objects.hashCode(this.client);
        hash = 89 * hash + Objects.hashCode(this.id);
        hash = 89 * hash + Objects.hashCode(this.type);
        hash = 89 * hash + Objects.hashCode(this.ruleID);
        hash = 89 * hash + Objects.hashCode(this.name);
        hash = 89 * hash + Objects.hashCode(this.multipleEmails);
        hash = 89 * hash + Objects.hashCode(this.description);
        hash = 89 * hash + Objects.hashCode(this.actionParams);
        hash = 89 * hash + Objects.hashCode(this.actionId);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final RuleAction other = (RuleAction) obj;
        if (!Objects.equals(this.client, other.client)) {
            return false;
        }
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        if (!Objects.equals(this.type, other.type)) {
            return false;
        }
        if (!Objects.equals(this.ruleID, other.ruleID)) {
            return false;
        }
        if (!Objects.equals(this.name, other.name)) {
            return false;
        }
        if (!Objects.equals(this.multipleEmails, other.multipleEmails)) {
            return false;
        }
        if (!Objects.equals(this.description, other.description)) {
            return false;
        }
        if (!Objects.equals(this.actionParams, other.actionParams)) {
            return false;
        }
        if (!Objects.equals(this.actionId, other.actionId)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
    	StringBuffer sb = new StringBuffer();
    	sb.append("RuleAction{")
    	.append(", client=" + client)
    	.append(", id=" + id)
    	.append(", type=" + type)
    	.append(", ruleID=" + ruleID)
    	.append(", name=" + name)
    	.append(", multipleEmails=" + multipleEmails)
    	.append(", description=" + description)
    	.append(", actionParams=" + actionParams)
    	.append(", actionId=" + actionId + "}");
        return sb.toString();
    }
    
   
}
