/* 
 * This class was generated by the JDS command line tool.
 * 
 * It was created by the user SBSS_19220038074936318185415652640319701600333637668158810727543328814
 * on the HANA system mo-d34b9d109:30015 
 * for CDS entities contained inside the schema 3F15CB45A62849F8834FFBA2B4C866CB.
 * 
 * Time of creation: 2016/09/22 14:15:49
 * 
 */
package com.sap.iot.ain.rules.models;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.util.Objects;
import javax.persistence.IdClass;

@Entity
@Table(name = "\"sap.ain.metaData::Rules.RuleJobSchedule\"")
@IdClass(RuleJobSchedulePK.class)
public class RuleJobSchedule implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @Column(name = "\"Client\"", nullable = true, length = 32)
    private String client;

    @Id
    @Column(name = "\"ID\"", nullable = false, length = 32)
    private String id;

    @Column(name = "\"Name\"", length = 255)
    private String name;

    @Column(name = "\"Status\"", length = 10)
    private String status;

    public String getClient() {
        return client;
    }

    public void setClient(String client) {
        this.client = client;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 23 * hash + Objects.hashCode(this.client);
        hash = 23 * hash + Objects.hashCode(this.id);
        hash = 23 * hash + Objects.hashCode(this.name);
        hash = 23 * hash + Objects.hashCode(this.status);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final RuleJobSchedule other = (RuleJobSchedule) obj;
        if (!Objects.equals(this.client, other.client)) {
            return false;
        }
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        if (!Objects.equals(this.name, other.name)) {
            return false;
        }
        if (!Objects.equals(this.status, other.status)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "RuleJobSchedule{" + "client=" + client + ", id=" + id + ", name=" + name + ", status=" + status + '}';
    }
    
}
