/* 
 * This class was generated by the JDS command line tool.
 * 
 * It was created by the user SBSS_19220038074936318185415652640319701600333637668158810727543328814
 * on the HANA system mo-d34b9d109:30015 
 * for CDS entities contained inside the schema 3F15CB45A62849F8834FFBA2B4C866CB.
 * 
 * Time of creation: 2016/10/04 15:24:02
 * 
 */
package com.sap.iot.ain.rules.models;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import javax.persistence.IdClass;

@Entity
@Table(name = "\"sap.ain.metaData::Rules.RuleRunResult\"")
@IdClass(RuleRunResultPK.class)
public class RuleRunResult implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @Column(name = "\"Client\"", nullable = true, length = 32)
    private String client;

    @Id
    @Column(name = "\"ID\"", nullable = true, length = 32)
    private String id;

    @Column(name = "\"RunID\"", length = 32)
    private String runId;

    @Column(name = "\"Value\"", length = 200)
    private String value;

    public String getClient() {
        return client;
    }

    public void setClient(String client) {
        this.client = client;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getRunId() {
        return runId;
    }

    public void setRunId(String runId) {
        this.runId = runId;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    @Override
    public String toString() {
        return "RuleRunResult{" + "client=" + client + ", id=" + id + ", runId=" + runId + ", value=" + value + '}';
    }

}
